spring:
  application:
    name: product-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8900
  flyway:
    baseline-on-migrate: true
grpc:
  server:
    port: 9920