spring:
  application:
    name: config-service
  profiles:
    active: jdbc
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT key, value FROM properties WHERE application=? AND profile=? AND label=?;
        order: 0
        default-label: master
    bus:
      trace:
        enabled: true
  flyway:
    baseline-on-migrate: true

server:
  port: 8900